FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim AS common-python-base

# tiangolo/uvicorn-gunicorn:python3.9
# tiangolo/uvicorn-gunicorn:python3.8-alpine3.10-slim

WORKDIR /pydist

RUN echo "updating package index"
RUN apt update

RUN echo "installing build platform dependencies"
RUN apt install -y gcc python3-dev build-essential libpq-dev python3-psycopg2 

RUN echo "installing and upgrading pip"
RUN /usr/local/bin/python -m pip install --upgrade pip

COPY codebase/ .
